/*
 * @Author: Chen Xin
 * @Date: 2022-04-11 21:33:57
 * @LastEditTime: 2022-04-11 21:52:37
 * @LastEditors: Chen Xin
 * @Description:
 * @FilePath: \Henin-Admin\auto-imports.d.ts
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {}
export {}
