/*
 * @Author: Chen Xin
 * @Date: 2022-03-21 11:34:17
 * @LastEditTime: 2022-04-11 16:13:06
 * @LastEditors: Chen Xin
 * @Description:
 * @FilePath: \xen-Admin\components.d.ts
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    HelloWorld: typeof import('@components/HelloWorld.vue')['default'];
  }
}

export {};
