// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Edit: typeof import('./src/components/edit.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconvElse: typeof import('element-plus/es')['ElIconvElse']
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HIcon: typeof import('./src/components/HIcon.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IRiAlertLine: typeof import('~icons/ri/alert-line')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
    IRiArrowLeftCircleLine: typeof import('~icons/ri/arrow-left-circle-line')['default']
    IRiArrowLeftCircleLinearrowRightCircleLine: typeof import('~icons/ri/arrow-left-circle-linearrow-right-circle-line')['default']
    IRiArrowRightCircleLine: typeof import('~icons/ri/arrow-right-circle-line')['default']
    IRiDashboardLine: typeof import('~icons/ri/dashboard-line')['default']
    IRiFullscreenExitFill: typeof import('~icons/ri/fullscreen-exit-fill')['default']
    IRiFullscreenFill: typeof import('~icons/ri/fullscreen-fill')['default']
    IRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IRiSettings3Line: typeof import('~icons/ri/settings3-line')['default']
    ITablerAccessibility: typeof import('~icons/tabler/accessibility')['default']
    ITablerAlertCircle: typeof import('~icons/tabler/alert-circle')['default']
    ITablerAntennaBars1: typeof import('~icons/tabler/antenna-bars1')['default']
  }
}

export { }
