// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/breadcrumb.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
  }
}

export { }
